### ISSUE TITLE
[Bug Report] form designer 官网 表单项配置响应器页面报错

### ISSUE THREAD

**Issue by dozedoze** [alibaba/designable#361]
form designer 官网 
在配置表单项配置响应器（ui隐藏\显示）的时候整个页面报错崩溃了

 **报错内容：**
 react-dom.production.min.js:121 TypeError: Cannot read properties of undefined (reading '0')
    at x-reactions (index.tsx:237:63)
    at transformer.js:138:24
    at internals.js:990:85
    at internals.js:102:59
    at r (internals.js:84:27)
    at internals.js:102:20
    at r (autorun.js:28:17)
    at reaction.js:198:13
    at e.forEachDelete (array.js:44:13)
    at G (reaction.js:193:22)

**Comment by lijie1024512** [comment]
这个项目暂时已经不维护了

**Comment by dengying918** [comment]
没有任何文档啊

**Comment by lijie1024512** [comment]
看源码 b站也有简单的项目整体分析的视频
